import { plainToInstance } from 'class-transformer';
import { validateSync } from 'class-validator';
import * as fs from 'fs';
import * as path from 'path';
import { ConfigService } from '@nestjs/config';
import { AiVerificationWebhookDto } from '../src/webhooks/dto/ai-verification-webhook.dto';
import { HmacService } from '../src/common/hmac/hmac.service';

describe('Cross-Service Contract Tests', () => {
  const fixturesDir = path.join(__dirname, '../../../tests/fixtures/contract');
  const secret = 'test-hmac-secret-32-chars-long!!';

  it('should perfectly validate the callback payload fixture', () => {
    // 1. Load the shared JSON fixture
    const payloadPath = path.join(fixturesDir, 'callback_payload.json');
    const fixtureBytes = fs.readFileSync(payloadPath);
    const fixtureObj = JSON.parse(fixtureBytes.toString());

    // 2. Transform the plain object to our DTO class instance
    const dtoInstance = plainToInstance(AiVerificationWebhookDto, fixtureObj);

    // 3. Validate using class-validator decorators
    // If this fails, the AI service generated a payload that drifts from our assumptions
    const errors = validateSync(dtoInstance);

    expect(errors.length).toBe(0);

    // Check that properties were actually set correctly
    expect(dtoInstance.taskId).toBe('task-abc-123');
    expect(dtoInstance.status).toBe('completed');
  });

  it('should verify the HMAC signature from the headers fixture', () => {
    // 1. Load both the payload and headers
    const payloadPath = path.join(fixturesDir, 'callback_payload.json');
    const payloadStr = fs.readFileSync(payloadPath).toString();

    const headersPath = path.join(fixturesDir, 'callback_headers.json');
    const headersStr = fs.readFileSync(headersPath).toString();
    const expectedHeaders = JSON.parse(headersStr);

    // 2. Setup the HmacService with the test secret
    const configServiceMock = {
      getOrThrow: jest.fn().mockReturnValue(secret),
    } as unknown as ConfigService;

    const hmacService = new HmacService(configServiceMock);

    // 3. Verify that our backend HmacService correctly validates the signature
    // generated by the AI-service
    const isSignatureValid = hmacService.verify(
      payloadStr,
      expectedHeaders['X-Signature-256'],
    );
    expect(isSignatureValid).toBe(true);
  });
});
